import { InventoryItem, MenuItem, Reservation, GalleryItem, DietaryTagInfo, CafeTable, RestockOrder } from '../types';

export const DIETARY_TAGS_META: Record<string, DietaryTagInfo> = {
  VG: {
    tag: 'VG',
    label: 'Vegan',
    fullName: '100% Plant-Based (Vegan)',
    colorClass: 'text-emerald-800',
    bgClass: 'bg-emerald-50',
    borderClass: 'border-emerald-200',
    description: 'Contains zero animal products, eggs, honey, or dairy.',
  },
  V: {
    tag: 'V',
    label: 'Vegetarian',
    fullName: 'Vegetarian',
    colorClass: 'text-green-800',
    bgClass: 'bg-green-50',
    borderClass: 'border-green-200',
    description: 'Plant-forward recipe; may contain ethically sourced dairy or eggs.',
  },
  GF: {
    tag: 'GF',
    label: 'Gluten-Free',
    fullName: 'Gluten-Free Recipe',
    colorClass: 'text-amber-800',
    bgClass: 'bg-amber-50',
    borderClass: 'border-amber-200',
    description: 'Crafted without gluten-containing grains (cross-contact protocol followed).',
  },
  DF: {
    tag: 'DF',
    label: 'Dairy-Free',
    fullName: 'Dairy-Free',
    colorClass: 'text-sky-800',
    bgClass: 'bg-sky-50',
    borderClass: 'border-sky-200',
    description: 'Prepared using organic oat, almond, or coconut milk alternatives.',
  },
  N: {
    tag: 'N',
    label: 'Contains Nuts',
    fullName: 'Nut Allergen Alert',
    colorClass: 'text-orange-800',
    bgClass: 'bg-orange-50',
    borderClass: 'border-orange-200',
    description: 'Contains tree nuts (almonds, pistachios, hazelnuts, or walnuts).',
  },
};

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-01',
    name: 'Ethiopia Yirgacheffe Grade 1 (Natural)',
    sku: 'RAW-ETH-001',
    category: 'Raw Ingredients',
    unit: 'kg',
    quantity: 18.5,
    minThreshold: 15.0,
    unitCost: 850.00,
    price: 1800.00,
    supplier: 'Direct Origin Importers Ltd',
    supplierPhone: '+91 98201 44821',
    supplierEmail: 'orders@directorigins.coffee',
    location: 'Roastery Green Silo #2',
    imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=600&q=80',
    isArchived: false,
    updatedAt: Date.now() - 1000 * 60 * 60 * 2,
    notes: 'Jasmine, bergamot, and ripe blueberry tasting profile. 2026 harvest.'
  },
  {
    id: 'inv-02',
    name: 'Colombia Huila Supremo (Washed)',
    sku: 'RAW-COL-002',
    category: 'Raw Ingredients',
    unit: 'kg',
    quantity: 6.0,
    minThreshold: 12.0,
    unitCost: 720.00,
    price: 1550.00,
    supplier: 'Andean Specialty Beans',
    supplierPhone: '+91 98201 78921',
    supplierEmail: 'supply@andeancoffee.co',
    location: 'Roastery Green Silo #1',
    imageUrl: 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?auto=format&fit=crop&w=600&q=80',
    isArchived: false,
    updatedAt: Date.now() - 1000 * 60 * 60 * 12,
    notes: 'Low stock warning! High demand for house espresso blend.'
  },
  {
    id: 'inv-03',
    name: 'Organic Ceremonial Uji Matcha',
    sku: 'RAW-MTC-003',
    category: 'Raw Ingredients',
    unit: 'kg',
    quantity: 1.2,
    minThreshold: 2.0,
    unitCost: 4500.00,
    price: 8500.00,
    supplier: 'Kyoto Heritage Tea Estate',
    supplierPhone: '+81 75 921 4400',
    supplierEmail: 'export@kyotomatcha.jp',
    location: 'Barista Cold Vault A',
    imageUrl: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=600&q=80',
    isArchived: false,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24,
    notes: 'First harvest stone ground. Kept in nitrogen-flushed tins.'
  },
  {
    id: 'inv-04',
    name: 'Valrhona 70% Guanaja Dark Cocoa Drops',
    sku: 'RAW-CHOC-004',
    category: 'Raw Ingredients',
    unit: 'kg',
    quantity: 8.5,
    minThreshold: 5.0,
    unitCost: 1600.00,
    price: 3200.00,
    supplier: 'Gourmet Artisan Pantry Co.',
    supplierPhone: '+91 98202 11330',
    supplierEmail: 'accounts@gourmetpantry.com',
    location: 'Bakery Dry Shelf C3',
    imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=600&q=80',
    isArchived: false,
    updatedAt: Date.now() - 1000 * 60 * 60 * 48,
    notes: 'For signature mocha and pain au chocolat.'
  },
  {
    id: 'inv-05',
    name: 'Oatly Barista Edition Oat Milk (Case of 6L)',
    sku: 'DRY-OAT-005',
    category: 'Dairy & Alt',
    unit: 'boxes',
    quantity: 24,
    minThreshold: 10,
    unitCost: 1100.00,
    price: 1800.00,
    supplier: 'Nordic Provisions Dist.',
    supplierPhone: '+91 98204 41998',
    supplierEmail: 'orders@nordicprovisions.com',
    location: 'Walk-In Chiller Bay 2',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=600&q=80',
    isArchived: false,
    updatedAt: Date.now() - 1000 * 60 * 60 * 5,
  },
  {
    id: 'inv-06',
    name: 'Organic Whole Milk (Gallon / 4L)',
    sku: 'DRY-MLK-006',
    category: 'Dairy & Alt',
    unit: 'units',
    quantity: 2,
    minThreshold: 8,
    unitCost: 280.00,
    price: 450.00,
    supplier: 'Farm Fresh Organic Creamery',
    supplierPhone: '+91 98205 23167',
    supplierEmail: 'dairy@farmfresh.com',
    location: 'Walk-In Chiller Bay 1',
    imageUrl: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=600&q=80',
    isArchived: false,
    updatedAt: Date.now() - 1000 * 60 * 30,
    notes: 'CRITICAL LOW STOCK: Only 2 gallons left on hand!'
  },
  {
    id: 'inv-07',
    name: 'French Cultured Butter (84% Butterfat)',
    sku: 'BAK-BTR-007',
    category: 'Bakery & Pantry',
    unit: 'kg',
    quantity: 14.0,
    minThreshold: 8.0,
    unitCost: 850.00,
    price: 1450.00,
    supplier: 'Normandy Artisan Imports',
    supplierPhone: '+91 98206 62771',
    supplierEmail: 'logistics@normandyimports.fr',
    location: 'Pastry Cold Room Rack 1',
    imageUrl: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=600&q=80',
    isArchived: false,
    updatedAt: Date.now() - 1000 * 60 * 60 * 18,
    notes: 'Crucial for morning croissant laminations.'
  },
  {
    id: 'inv-08',
    name: 'Organic T55 French Pastry Flour (25kg Bag)',
    sku: 'BAK-FLR-008',
    category: 'Bakery & Pantry',
    unit: 'bags',
    quantity: 5,
    minThreshold: 3,
    unitCost: 2400.00,
    price: 3600.00,
    supplier: 'Moulins Viron Paris',
    supplierPhone: '+33 1 40 22 88 00',
    supplierEmail: 'farine@moulinsviron.com',
    location: 'Bakery Flour Dry Store',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
    isArchived: false,
    updatedAt: Date.now() - 1000 * 60 * 60 * 8,
  },
  {
    id: 'inv-09',
    name: '"Dawn Mist" Yirgacheffe Retail Tin (250g)',
    sku: 'RET-COF-009',
    category: 'Retail Coffee Beans',
    unit: 'units',
    quantity: 18,
    minThreshold: 10,
    unitCost: 420.00,
    price: 850.00,
    supplier: 'In-House Aura Micro-Roastery',
    supplierPhone: '+91 98200 28721',
    supplierEmail: 'roastery@auracoffee.com',
    location: 'Retail Display Shelf 1',
    imageUrl: 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?auto=format&fit=crop&w=600&q=80',
    isArchived: false,
    updatedAt: Date.now() - 1000 * 60 * 60 * 6,
  },
  {
    id: 'inv-10',
    name: '"Velvet Nocturne" Dark Roast Retail Tin (250g)',
    sku: 'RET-COF-010',
    category: 'Retail Coffee Beans',
    unit: 'units',
    quantity: 0,
    minThreshold: 8,
    unitCost: 390.00,
    price: 790.00,
    supplier: 'In-House Aura Micro-Roastery',
    supplierPhone: '+91 98200 28721',
    supplierEmail: 'roastery@auracoffee.com',
    location: 'Retail Display Shelf 1',
    imageUrl: 'https://images.unsplash.com/photo-1610632380989-680fe40816c6?auto=format&fit=crop&w=600&q=80',
    isArchived: false,
    updatedAt: Date.now() - 1000 * 60 * 15,
    notes: 'OUT OF STOCK: Batch roasting scheduled for Thursday.'
  },
  {
    id: 'inv-11',
    name: '12oz Compostable Sugarcane Cups (Sleeve of 50)',
    sku: 'PKG-CUP-011',
    category: 'Packaging',
    unit: 'packs',
    quantity: 42,
    minThreshold: 15,
    unitCost: 280.00,
    price: 550.00,
    supplier: 'EcoPackaging Solutions',
    supplierPhone: '+91 98207 74129',
    supplierEmail: 'sales@ecopacksolutions.com',
    location: 'Storage Loft Rack D',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    isArchived: false,
    updatedAt: Date.now() - 1000 * 60 * 60 * 40,
  },
  {
    id: 'inv-12',
    name: 'CPLA Plant-Based Hot Cup Lids (Pack of 100)',
    sku: 'PKG-LID-012',
    category: 'Packaging',
    unit: 'packs',
    quantity: 4,
    minThreshold: 12,
    unitCost: 350.00,
    price: 680.00,
    supplier: 'EcoPackaging Solutions',
    supplierPhone: '+91 98207 74129',
    supplierEmail: 'sales@ecopacksolutions.com',
    location: 'Storage Loft Rack D',
    imageUrl: 'https://images.unsplash.com/photo-1577937927133-66ef06acdf18?auto=format&fit=crop&w=600&q=80',
    isArchived: false,
    updatedAt: Date.now() - 1000 * 60 * 60 * 3,
    notes: 'LOW STOCK: Reorder pending shipment.'
  },
  {
    id: 'inv-13',
    name: 'Bourbon Madagascar Vanilla Beans (Pack of 20)',
    sku: 'RAW-VAN-013',
    category: 'Raw Ingredients',
    unit: 'packs',
    quantity: 8,
    minThreshold: 4,
    unitCost: 1800.00,
    price: 3200.00,
    supplier: 'Equatorial Spices Guild',
    supplierPhone: '+91 98204 31890',
    supplierEmail: 'orders@equatorialspices.com',
    location: 'Bakery Spice Safe',
    imageUrl: 'https://images.unsplash.com/photo-1608797178974-15b35a61dede?auto=format&fit=crop&w=600&q=80',
    isArchived: false,
    updatedAt: Date.now() - 1000 * 60 * 60 * 72,
  },
  {
    id: 'inv-14',
    name: 'Unbleached Kraft Carry Bags (Box of 250)',
    sku: 'PKG-BAG-014',
    category: 'Packaging',
    unit: 'boxes',
    quantity: 11,
    minThreshold: 5,
    unitCost: 1200.00,
    price: 2100.00,
    supplier: 'EcoPackaging Solutions',
    supplierPhone: '+91 98207 74129',
    supplierEmail: 'sales@ecopacksolutions.com',
    location: 'Storage Loft Rack B',
    imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=600&q=80',
    isArchived: false,
    updatedAt: Date.now() - 1000 * 60 * 60 * 100,
  }
];

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  {
    id: 'menu-01',
    name: 'Valencia Orange Peel Cortado',
    category: 'Espresso & Specialty Coffee',
    price: 280.00,
    description: 'Double ristretto extracted over expressed organic Valencia orange zest, balanced with velvety textured milk in a 4oz Gibraltar glass.',
    dietaryTags: ['GF', 'V'],
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=800&q=80',
    prepTime: '3-4 mins',
    tastingNotes: ['Bright Citrus', 'Dark Chocolate', 'Silky Cream'],
    featured: true,
  },
  {
    id: 'menu-02',
    name: 'Velvet Fleur de Sel Macchiato',
    category: 'Espresso & Specialty Coffee',
    price: 310.00,
    description: 'Espresso poured through house-cooked butter caramel, finished with cold dense foam and sea salt flakes.',
    dietaryTags: ['GF', 'V'],
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1485808191679-5f86510681a2?auto=format&fit=crop&w=800&q=80',
    prepTime: '4 mins',
    tastingNotes: ['Salted Toffee', 'Roasted Hazelnut', 'Toasted Sugar'],
    featured: true,
  },
  {
    id: 'menu-03',
    name: 'Ethiopia Yirgacheffe V60 Pour-Over',
    category: 'Espresso & Specialty Coffee',
    price: 340.00,
    description: 'Single-origin microlot brewed precisely at 93°C on Hario V60 with 1:16 ratio. High floral aromatics and lingering sweetness.',
    dietaryTags: ['VG', 'GF', 'DF'],
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    prepTime: '5 mins',
    tastingNotes: ['Jasmine Florals', 'Bergamot', 'Wild Raspberry'],
    featured: true,
  },
  {
    id: 'menu-04',
    name: 'Smoked Cardamom Spanish Latte',
    category: 'Espresso & Specialty Coffee',
    price: 320.00,
    description: 'Slow-simmered condensed milk infused with green cardamom pods, topped with double espresso and smoked cinnamon foam.',
    dietaryTags: ['V', 'GF'],
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=800&q=80',
    prepTime: '4 mins',
    tastingNotes: ['Cardamom Pods', 'Smoked Cinnamon', 'Dulce de Leche'],
    featured: false,
  },
  {
    id: 'menu-05',
    name: 'Kyoto 18-Hour Slow-Drip Cold Brew',
    category: 'Cold Brews & Teas',
    price: 330.00,
    description: 'Gravity-extracted drop-by-drop over 18 hours using Japanese Oji towers. Ultra-clarified, zero bitterness, served over clear ice.',
    dietaryTags: ['VG', 'GF', 'DF'],
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=800&q=80',
    prepTime: 'Instant',
    tastingNotes: ['Dark Cocoa', 'Cognac Oak', 'Sweet Molasses'],
    featured: true,
  },
  {
    id: 'menu-06',
    name: 'Ceremonial Uji Iced Matcha Latte',
    category: 'Cold Brews & Teas',
    price: 360.00,
    description: 'First-harvest Japanese tencha green tea whisked with bamboo chasen, layered over iced oat milk and raw Madagascar vanilla.',
    dietaryTags: ['VG', 'GF', 'DF'],
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=800&q=80',
    prepTime: '3-4 mins',
    tastingNotes: ['Umami Grassiness', 'Vanilla Bean', 'Creamy Oat'],
    featured: false,
  },
  {
    id: 'menu-07',
    name: 'Sparkling Cascara & Grapefruit Spritz',
    category: 'Cold Brews & Teas',
    price: 290.00,
    description: 'Sun-dried organic coffee cherry tea carbonated with fresh pink grapefruit juice and fresh rosemary sprig.',
    dietaryTags: ['VG', 'GF', 'DF'],
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
    prepTime: '2-3 mins',
    tastingNotes: ['Rosehip', 'Tart Citrus', 'Herbal Crisp'],
    featured: false,
  },
  {
    id: 'menu-08',
    name: '72-Hour Fermented Sourdough Croissant',
    category: 'Artisan Bakery',
    price: 240.00,
    description: 'Wild yeast lamination using 84% butterfat Normandy butter. 27 delicate honeycomb layers, baked daily at 6:30 AM.',
    dietaryTags: ['V'],
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80',
    prepTime: 'Warm on request',
    tastingNotes: ['Cultured Butter', 'Toasted Flake', 'Subtle Tang'],
    featured: true,
  },
  {
    id: 'menu-09',
    name: 'Pistachio & Rosewater Cruffin',
    category: 'Artisan Bakery',
    price: 290.00,
    description: 'Croissant pastry baked in a muffin tin, filled with silky Sicilian pistachio cream and dusted with rosewater powdered sugar.',
    dietaryTags: ['V', 'N'],
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    prepTime: 'Ready to serve',
    tastingNotes: ['Roasted Pistachio', 'Rose Petal', 'Crisp Caramel'],
    featured: false,
  },
  {
    id: 'menu-10',
    name: 'Valrhona Babka Twist',
    category: 'Artisan Bakery',
    price: 270.00,
    description: 'Rich brioche braided with 70% dark Valrhona chocolate, toasted hazelnuts, and simple orange blossom syrup glaze.',
    dietaryTags: ['V', 'N'],
    isAvailable: false,
    imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=800&q=80',
    prepTime: 'Sold Out Today',
    tastingNotes: ['Dark Cocoa', 'Toasted Hazelnut', 'Buttery Brioche'],
    featured: false,
  },
  {
    id: 'menu-11',
    name: 'Avocado Tartine on Seeded Sourdough',
    category: 'All-Day Brunch',
    price: 420.00,
    description: 'Hass avocado mash, heirloom cherry tomatoes, Aleppo chili oil, toasted sesame, and pomegranate reduction on grilled country loaf.',
    dietaryTags: ['VG', 'DF'],
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80',
    prepTime: '8-10 mins',
    tastingNotes: ['Creamy Avocado', 'Zesty Sumac', 'Crusty Grain'],
    featured: true,
  },
  {
    id: 'menu-12',
    name: 'Truffled Wild Mushroom Toast',
    category: 'All-Day Brunch',
    price: 480.00,
    description: 'Pan-seared Chanterelle and King Oyster mushrooms, thyme whipped ricotta, white truffle oil, and poached pasture-raised egg.',
    dietaryTags: ['V'],
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80',
    prepTime: '10-12 mins',
    tastingNotes: ['Earthy Truffle', 'Whipped Ricotta', 'Herbal Thyme'],
    featured: false,
  },
  {
    id: 'menu-13',
    name: 'Shakshuka Provençale',
    category: 'All-Day Brunch',
    price: 450.00,
    description: 'Two poached farm eggs baked in spiced San Marzano tomato & bell pepper ragout, French sheep feta, fresh cilantro, served with grilled sourdough.',
    dietaryTags: ['V', 'GF'],
    isAvailable: true,
    imageUrl: 'https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=800&q=80',
    prepTime: '12-14 mins',
    tastingNotes: ['Cumin Tomato', 'Tangy Feta', 'Warm Hearth'],
    featured: false,
  }
];

export const INITIAL_RESERVATIONS: Reservation[] = [];

export const INITIAL_TABLES: CafeTable[] = [
  // Indoor Main Lounge
  { 
    id: 'tbl-01', 
    tableNumber: 'T-01', 
    name: 'Table 1 (Window Nook)', 
    seatingArea: 'Indoor Main Lounge', 
    capacity: 2, 
    minCapacity: 1,
    zone: 'Window',
    perks: ['Natural street window view', 'Near electrical outlets', 'Cozy duo table'],
    status: 'available',
    isActive: true
  },
  { 
    id: 'tbl-02', 
    tableNumber: 'T-02', 
    name: 'Table 2 (Window Nook)', 
    seatingArea: 'Indoor Main Lounge', 
    capacity: 2, 
    minCapacity: 1,
    zone: 'Window',
    perks: ['Quiet conversation spot', 'High-speed Wi-Fi proximity'],
    status: 'available',
    isActive: true
  },
  { 
    id: 'tbl-03', 
    tableNumber: 'T-03', 
    name: 'Table 3 (Central Oak)', 
    seatingArea: 'Indoor Main Lounge', 
    capacity: 4, 
    minCapacity: 2,
    zone: 'Indoor Main',
    perks: ['Artisan solid oak table', 'Spacious dining layout', 'Great acoustics'],
    status: 'available',
    isActive: true
  },
  { 
    id: 'tbl-04', 
    tableNumber: 'T-04', 
    name: 'Table 4 (Velvet Booth)', 
    seatingArea: 'Indoor Main Lounge', 
    capacity: 4, 
    minCapacity: 2,
    zone: 'Indoor Main',
    perks: ['Recessed plush velvet booth', 'Intimate dining', 'Top guest favorite'],
    status: 'available',
    isActive: true
  },
  { 
    id: 'tbl-05', 
    tableNumber: 'T-05', 
    name: 'Table 5 (Lounge Sofa Corner)', 
    seatingArea: 'Indoor Main Lounge', 
    capacity: 6, 
    minCapacity: 3,
    zone: 'Indoor Main',
    perks: ['Deep sectional sofa seating', 'Low coffee & brunch table', 'Accommodates larger groups'],
    status: 'available',
    isActive: true
  },
  
  // Sunlit Garden Patio
  { 
    id: 'tbl-06', 
    tableNumber: 'P-01', 
    name: 'Patio P1 (Bistro Duo)', 
    seatingArea: 'Sunlit Garden Patio', 
    capacity: 2, 
    minCapacity: 1,
    zone: 'Patio',
    perks: ['Covered outdoor greenery', 'Overhead radiant heaters', 'Al fresco breeze'],
    status: 'available',
    isActive: true
  },
  { 
    id: 'tbl-07', 
    tableNumber: 'P-02', 
    name: 'Patio P2 (Courtyard Quad)', 
    seatingArea: 'Sunlit Garden Patio', 
    capacity: 4, 
    minCapacity: 2,
    zone: 'Patio',
    perks: ['Surrounded by potted olive trees', 'Relaxed open-air dining', 'Natural sunlight'],
    status: 'available',
    isActive: true
  },
  { 
    id: 'tbl-08', 
    tableNumber: 'P-03', 
    name: 'Patio P3 (Olive Tree Pergola)', 
    seatingArea: 'Sunlit Garden Patio', 
    capacity: 6, 
    minCapacity: 4,
    zone: 'Patio',
    perks: ['Underneath wooden pergola', 'Private garden corner', 'Ideal for family brunch'],
    status: 'available',
    isActive: true
  },
  
  // Private Tasting Nook
  { 
    id: 'tbl-12', 
    tableNumber: 'N-01', 
    name: 'Private Nook N1 (Cupping Suite)', 
    seatingArea: 'Private Tasting Nook', 
    capacity: 8, 
    minCapacity: 4,
    zone: 'Private Nook',
    perks: ['Acoustically isolated room', 'Custom pottery display', 'Private tasting & meeting table'],
    status: 'available',
    isActive: true
  },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: 'gal-1',
    title: 'The Morning Extraction',
    caption: 'Dialing in our natural Ethiopia Yirgacheffe on our customized Slayer espresso machine.',
    category: 'Coffee Craft',
    imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80',
    aspectRatio: 'landscape'
  },
  {
    id: 'gal-2',
    title: 'Pacific Fog Lounge',
    caption: 'Designed with cool oak, ocean fog plaster, and artisan ceramics for mindful pauses.',
    category: 'Interiors',
    imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=80',
    aspectRatio: 'portrait'
  },
  {
    id: 'gal-3',
    title: '72-Hour Sourdough Viennoiserie',
    caption: 'Freshly baked laminated honeycomb croissants cooling on marble racks at 7:00 AM.',
    category: 'Bakery & Food',
    imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=1200&q=80',
    aspectRatio: 'landscape'
  },
  {
    id: 'gal-4',
    title: 'Hand-Poured Ceramic Tableware',
    caption: 'Each ceramic vessel is thrown locally by studio ceramicist Hannah Leigh.',
    category: 'Interiors',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1200&q=80',
    aspectRatio: 'square'
  },
  {
    id: 'gal-5',
    title: 'Cupping & Sensory Workshop',
    caption: 'Monthly community cupping sessions exploring acidities, processing styles, and micro-terroirs.',
    category: 'Community',
    imageUrl: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=1200&q=80',
    aspectRatio: 'landscape'
  },
  {
    id: 'gal-6',
    title: 'Matcha Whisking Ritual',
    caption: 'Ceremonial Uji matcha hand-whisked in traditional Chawan tea bowls.',
    category: 'Coffee Craft',
    imageUrl: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=1200&q=80',
    aspectRatio: 'portrait'
  },
  {
    id: 'gal-7',
    title: 'Sunlit Coastal Patio Courtyard',
    caption: 'Sheltered under olive trees with acoustic warmth and outdoor heaters.',
    category: 'Interiors',
    imageUrl: 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=1200&q=80',
    aspectRatio: 'landscape'
  },
  {
    id: 'gal-8',
    title: 'Avocado Tartine with Pomegranate Seeds',
    caption: 'Plated on our organic sourdough with zaatar and cold-pressed olive oil.',
    category: 'Bakery & Food',
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1200&q=80',
    aspectRatio: 'landscape'
  }
];

export const INITIAL_SAMPLE_RESTOCK_ORDERS: RestockOrder[] = [
  {
    id: 'po-101',
    orderNumber: 'PO-8842',
    supplierName: 'Blue Tokai Artisan Coffee Roasters',
    supplierPhone: '+91 98201 55432',
    supplierEmail: 'wholesale@bluetokaicoffee.com',
    items: [
      { itemId: 'inv-1', itemName: 'Ethiopia Yirgacheffe G1 Green Beans', quantityOrdered: 50, quantityReceived: 50, unit: 'kg', unitCost: 1800, totalCost: 90000 },
      { itemId: 'inv-2', itemName: 'Colombia Geisha Natural Roast', quantityOrdered: 20, quantityReceived: 20, unit: 'kg', unitCost: 3400, totalCost: 68000 }
    ],
    totalAmount: 158000,
    status: 'received',
    orderedAt: Date.now() - 1000 * 60 * 60 * 48,
    orderedBy: 'Aditya Patil (Head Roaster)',
    expectedDeliveryDate: 'Yesterday',
    receivedAt: Date.now() - 1000 * 60 * 60 * 18,
    receivedBy: 'Vikram Mehta (Shift Lead)',
    deliveryInvoiceNo: 'INV-BT-9931',
    notes: 'Green bean bags checked for moisture levels and sealed burlap sacks.'
  },
  {
    id: 'po-102',
    orderNumber: 'PO-8843',
    supplierName: 'Califia Farms & Oat Dairy Co.',
    supplierPhone: '+91 98334 11200',
    supplierEmail: 'orders@califiadistribution.in',
    items: [
      { itemId: 'inv-4', itemName: 'Califia Barista Oat Milk 1L', quantityOrdered: 120, quantityReceived: 120, unit: 'L', unitCost: 320, totalCost: 38400 },
      { itemId: 'inv-5', itemName: 'Almond Breeze Professional 1L', quantityOrdered: 60, quantityReceived: 60, unit: 'L', unitCost: 290, totalCost: 17400 }
    ],
    totalAmount: 55800,
    status: 'received',
    orderedAt: Date.now() - 1000 * 60 * 60 * 36,
    orderedBy: 'Vikram Mehta',
    expectedDeliveryDate: 'Yesterday',
    receivedAt: Date.now() - 1000 * 60 * 60 * 6,
    receivedBy: 'Ananya Sharma (Senior Barista)',
    deliveryInvoiceNo: 'INV-CF-4182',
    notes: 'Stored in walk-in chiller. Chilled temperature verified at 4°C.'
  },
  {
    id: 'po-103',
    orderNumber: 'PO-8844',
    supplierName: 'EcoPackaging & Compostable Labs',
    supplierPhone: '+91 98111 88722',
    supplierEmail: 'supply@ecopacklabs.in',
    items: [
      { itemId: 'inv-7', itemName: '12oz Double-Wall Kraft Hot Cups', quantityOrdered: 2000, unit: 'Units', unitCost: 8.5, totalCost: 17000 },
      { itemId: 'inv-8', itemName: 'Bagasse Embossed Sip Lids', quantityOrdered: 2000, unit: 'Units', unitCost: 4.2, totalCost: 8400 }
    ],
    totalAmount: 25400,
    status: 'ordered',
    orderedAt: Date.now() - 1000 * 60 * 60 * 12,
    orderedBy: 'Aditya Patil',
    expectedDeliveryDate: 'Tomorrow at 10:00 AM',
    notes: 'Standard replenishment batch for weekend high-volume service.'
  },
  {
    id: 'po-104',
    orderNumber: 'PO-8845',
    supplierName: 'Monsoon Malabar Organic Estates',
    supplierPhone: '+91 98450 77123',
    supplierEmail: 'estates@monsoonmalabar.com',
    items: [
      { itemId: 'inv-3', itemName: 'Sumatra Mandheling Single Origin', quantityOrdered: 40, unit: 'kg', unitCost: 1450, totalCost: 58000 }
    ],
    totalAmount: 58000,
    status: 'in_transit',
    orderedAt: Date.now() - 1000 * 60 * 60 * 20,
    orderedBy: 'Vikram Mehta',
    expectedDeliveryDate: 'Today by 4:00 PM',
    notes: 'Air freight dispatch from Karnataka estates.'
  }
];

